### ISSUE TITLE
Unable to change profile picture

### ISSUE THREAD

**Issue by karn09** [lpatmo/cb#12]
Can't change profile picture from initial photo

**Comment by lpatmo** [comment]
Thanks for filing! Yeah, unfortunately the avatar picture comes from gravatar or twitter, and there's no image upload capability built in.

See: https://github.com/TelescopeJS/Telescope/issues/356

**Comment by litnerdy** [comment]
Workaround in case anyone else is stuck on this:

Add an email that has a gravatar associated with it to your profile. It will pull in that image automatically.
