### ISSUE TITLE
Strange CSS issues - icons without profile images are rendered a few pixels down

### ISSUE THREAD

**Issue by lpatmo** [lpatmo/cb#16]
Example: http://hangouts.codebuddies.org/posts/kBiHb35NrbnJmRTnC

**Comment by rgjr** [comment]
First thing I noticed, too. Was going to submit an issue but saw you already put it up.

Looking through the stylesheet, I think a simple fix could be implemented in line 4166 by adding a [position: absolute] :

```
.members ul li .avatar-image, .members ul li .avatar-initials {
    height: 50px;
    width: 50px;
    position: absolute;     //Avatars line up nicely after adding this
}
```

Worked on Safari v.8.0.3 and Chrome v.38.0.2125.111 on a MBA 11", but resizing the browsers held the design changes. 

Lastly, I'm still a CSS newbie, so my apologies if my suggestion is not following best practices or looks hack-y. :)

**Comment by lpatmo** [comment]
Nice work, Raul. Thanks! Will push out this fix after I work out a few more non-related issues.
