### ISSUE TITLE
Simplify the list view

### ISSUE THREAD

**Issue by afeld** [lpatmo/cb#20]
I'm definitely _not_ a designer, but a few things that stood out about the listings:

![new_-_codebuddies_hangouts](https://cloud.githubusercontent.com/assets/86842/5625213/7d59b7b6-9544-11e4-9587-e7a9e232fc2d.png)
- "I'm interested!" and "Launch hangout" are repeated a bunch of times... useful the first time, but distracting after that. Maybe there's a way to simplify them down to icons or single words with a tooltip or something?
- The tags almost always repeat text in the title – I'd say just don't bother showing them in the rows.
- The list would be easier to scan (visually) if the dates/times were distinguished from the titles.

Hope that helps. Nice work!

**Comment by lpatmo** [comment]
W00t, thanks for the quick feedback, Aidan!
