### ISSUE TITLE
Give post submitters an option to send a reminder message to upvoters

### ISSUE THREAD

**Issue by lpatmo** [lpatmo/cb#22]
1. Return a list of e-mails of everyone who "upvoted" a post.
2. Only the submitter of the post will be able to see these e-mails. 
3. BONUS: The submitter of the post will see a textarea with a button, and write something in the text box to send an e-mail to the people who indicated interest in the hangout.

**Comment by delgermurun** [comment]
@lpatmo I'll work on it day after tomorrow. Is it appropriate?

**Comment by lpatmo** [comment]
@delgermurun Of course! Thanks for helping -- no rush. :) I'll see if I have something by then that I can also show.

**Comment by lpatmo** [comment]
Closed given that participants are notified when threads are updated -- thanks to a PR @delgermurun contributed to the core Telescope project.
