### ISSUE TITLE
Title has "Starting at..." well after the starting time of the hangout has passed.

### ISSUE THREAD

**Issue by RussEby** [lpatmo/cb#34]
After the hangout has occurred, the title will still have "Starting" with the past time of the start.

For example: 
A HTML/CSS hangout that occurred on Saturday 2/21/15 still stated on Sunday 2/22/15 that is was "Starting a day ago". Another, a SASS Knowledge Sharing has "Starting 17 hours ago".

Expected:
I would expect that they would change to "Started" after the start time.

**Comment by lpatmo** [comment]
Thanks for filing this bug, Russ!

**Comment by lpatmo** [comment]
Should be fixed now. Hangouts that have started are marked "IN PROGRESS."

**Comment by lpatmo** [comment]
See: https://github.com/lpatmo/cb/commit/3b7caa8c69f575785b6e9b3bc78f8f7d04de82aa
