### ISSUE TITLE
codebuddies.org Top-center 

### ISSUE THREAD

**Issue by lwgray** [lpatmo/cb#37]
The Codebuddies.org link at the top center of the screen overlaps with username.
![screenshot 2015-03-02 20 34 37](https://cloud.githubusercontent.com/assets/1000117/6454910/a8900702-c11b-11e4-81c9-a16d340a5676.png)

**Comment by lpatmo** [comment]
Ahh, thanks! That's definitely now how it looks on my screen 
![screen shot 2015-03-03 at 1 17 09 am](https://cloud.githubusercontent.com/assets/4512699/6457377/1115e978-c143-11e4-95d9-aea3303c32da.png)

I'm guessing that you're on a Windows 7 or 8 machine running Chrome?

**Comment by wuworkshop** [comment]
I'm actually getting the same issue in Chrome 40 and Firefox 36 on OS X Yosemite 10.10.2. Comparing the screenshots and looking at the CSS, it looks like we're rendering a different font in the font stack. "Source Sans Pro" isn't loading for us. Chrome Dev Tools shows "Helvetica Neue" as the Rendered Font. Are you using Google Fonts?

![screen shot 2015-03-03 at 2 57 06 am](https://cloud.githubusercontent.com/assets/605787/6458556/da03e2e0-c152-11e4-8812-c63140604b35.png)

Regardless of which font the user has, maybe text should just drop below the CB logo?

**Comment by lpatmo** [comment]
Got rid fo the upper-right-hand button; hopefully this fixed it.
