### ISSUE TITLE
Add a datepicker module to forms and re-order using this view.

### ISSUE THREAD

**Issue by lpatmo** [lpatmo/cb#4]
OR: un-hide the current datepicker that only admins can see, and add time zone support to it.

**Comment by lpatmo** [comment]
UPDATE: Re-write forms to add a datepicker, and re-order hangouts using this new view. Also divide up hangouts by "upcoming" vs. "previous hangouts." Bonus: have the date/time show up separately based on this datepicker time instead of putting it in the title.

**Comment by curioussavage** [comment]
Looks like commit 2bbec58 partially addressed this. Maybe this could be closed and a new issue created for the display of hangouts being divided into upcoming v previous

**Comment by lpatmo** [comment]
@curioussavage Yep, thanks! Good reminder that I should review all these issues and do a bit of cleanup.
