### ISSUE TITLE
Wow, mobile view is pretty broken.

### ISSUE THREAD

**Issue by lpatmo** [lpatmo/cb#56]
Must fix!

**Comment by Hommus** [comment]
I'm viewing it now and there doesn't seem to be much of a problem. What device were you using at the time?

**Comment by lpatmo** [comment]
@Paulie-P I fixed most of it but didn't update here. -_- The remaining issue is that the mobile nav icon on the top left shifts up when the user tries to click on it.

**Comment by Hommus** [comment]
@lpatmo I think I've fixed it. How do I go about creating branches so you can see what changes I've made?

**Comment by lpatmo** [comment]
@Paulie-P Merged! It'll go out in the next deploy. :) Thanks much for being the third-ever PR contributor to this repo!

(Also sorry I only saw your comment now. I noticed the pull request today.)

![firework1](https://cloud.githubusercontent.com/assets/4512699/7333310/a2f105a2-eb38-11e4-907b-75b8e9dddd7a.gif)
