### ISSUE TITLE
Dates/times disappear on Safari 8.0.5

### ISSUE THREAD

**Issue by lpatmo** [lpatmo/cb#63]
Thanks @dbgrandi for finding this bug!

**Comment by wuworkshop** [comment]
I figured out the culprit. It's your `formattedHangoutDate` function in new_post_title.js. Safari doesn't seem to understand `Intl.DateTimeFormat().resolvedOptions().timeZone`. It throws a ReferenceError:

>  ReferenceError: Can't find variable: Intl. 

Chrome understands it and Firefox just gives you `undefined`. If you want to see what I'm talking about, run these commands in the browser consoles:

```
new Date();
Intl.DateTimeFormat().resolvedOptions().timeZone;
```

Just came across this comment in the moment-timezone repo:
https://github.com/moment/moment-timezone/issues/138#issuecomment-77940479

`Intl.DateTimeFormat().resolvedOptions().timeZone` seems to only work in the latest Chrome and Opera (at least in my Mac versions, haven't checked Windows).

**Comment by lpatmo** [comment]
Resolved by @wuworkshop! Fourth person to make a pull request to /cb!

![firework1](https://cloud.githubusercontent.com/assets/4512699/7458580/7aa6a458-f263-11e4-9901-140d2e647237.gif)
